route:
  receiver: 'mail'
  repeat_interval: 4h
  group_by: [ alertname ]


receivers:
- name: 'mail'
  email_configs:
  - to: secret
    from: secret
    smarthost: smtp.gmail.com:587
    auth_username: secret
    auth_identity: secret
    auth_password: secret
    send_resolved: true

