version: "3"
services:
  web:
    container_name: web
    build:
      context: .
      dockerfile: Dockerfile.dockerfile
    ports: 
      - "5000:5000"
  redis:
    container_name: redis
    image: "redis:alpine"